---
title: "Graficacion en ggplot2 y quarto"
format: 
  html: 
    toc: true
    lang: es
---

# Introducción

Este documento presenta un conjunto de visualizaciones de datos elaborados con paquetes del lenguaje R como ggplot2, ploty y DT.

# Carga de bibliotecas

```{r}
#| label:  carga-bibliotecas
#| warning: false

library(tidyverse)
library(plotly)
library(DT)
library(gapminder)


```

# Carga de datos

```{r}
#| label: carga de datos
#| warning: false  
#| code-fold: true

#Carga de datos del paquete mpg

mpg |>
  datatable(options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## Diamonds

```{r}
#| label: carga_de_datos_diamonds 
#| warning: false  
#| code-fold: true

#Carga de datos del paquete diamonds

diamonds |>
  datatable(options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## Gapminder

```{r}
#| label: carga de datos gapminder 
#| warning: false  
#| code-fold: true

#Carga de datos del paquete gapminder

gapminder |>
  filter(year == 2007) |>
  datatable(options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## COVID

```{r}
#| label: carga de datos COVID 
#| warning: false 
#| code-fold: true


# Carga del archivo CSV de entrada en un dataframe
# con la función read_delim() de readr
covid_general <-
  read_delim(
    file = "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2023-i/main/datos/ministerio-salud/covid/05_30_22_CSV_GENERAL.csv",
    col_select = c(
      "FECHA",
      "positivos",
      "activos",
      "RECUPERADOS",
      "fallecidos",
      "nue_posi",
      "nue_falleci",
      "salon",
      "UCI"
    )
  )

# Cambio de nombre de columnas
covid_general <-
  covid_general |>
  rename(
    fecha = FECHA,
    recuperados = RECUPERADOS,
    nuevos_positivos = nue_posi,
    nuevos_fallecidos = nue_falleci,
    uci = UCI
  )

# Cambio de tipo de datos de la columna fecha, de str a date
covid_general <-
  covid_general |>
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))


# Despliegue de datos 

covid_general |>
  datatable(options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )


```

## Delitos 2022

```{r}
#| label: carga de datos Delitos 2022
#| warning: false 
#| code-fold: true

# Carga de datos
delitos_2022 <-
  read_delim(
    file = "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2023-i/main/datos/oij/estadisticas-policiales/estadisticaspoliciales2022.csv"
  )

# Tabla de datos
delitos_2022 |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```



